CREATE DATABASE LocadoraDb

GO

USE LocadoraDb

CREATE TABLE [user]
(
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Email] VARCHAR(40) NOT NULL,
[Password] VARCHAR(40) NOT NULL
)

GO

CREATE TABLE tb_Cliente(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL)

GO

CREATE TABLE tb_Filme(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50) NOT NULL,
DISPONIVEL BIT NOT NULL)

GO

CREATE TABLE tb_Locacoes(
ID INT PRIMARY KEY IDENTITY(1,1),
ID_CLIENTE INT NOT NULL,
ID_FILME INT NOT NULL,
DT_LOCACAO DATE NOT NULL,
DT_DEVOLUCAO DATE NULL,
DT_ENTRADA DATE NULL)

GO

ALTER TABLE tb_Locacoes
ADD CONSTRAINT fk_id_cliente FOREIGN KEY (ID_CLIENTE)
REFERENCES tb_Cliente (ID)

GO

ALTER TABLE tb_Locacoes
ADD CONSTRAINT fk_id_filme FOREIGN KEY (ID_FILME)
REFERENCES tb_Filme (ID)